-- MySQL Script generated by MySQL Workbench
-- 09/27/17 13:31:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`palavras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`palavras` (
  `id` INT NOT NULL,
  `palavra` VARCHAR(45) NULL,
  `pronuncia` VARCHAR(45) NULL,
  `origem` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`significado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`significado` (
  `id` INT NOT NULL,
  `significado` VARCHAR(45) NULL,
  `palavras_id` INT NOT NULL,
  PRIMARY KEY (`id` , `palavras_id`),
  INDEX `fk_significado_palavras1_idx` (`palavras_id` ASC),
  CONSTRAINT `fk_significado_palavras1`
    FOREIGN KEY (`palavras_id`)
    REFERENCES `mydb`.`palavras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sinonimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sinonimo` (
  `palavras_id` INT NOT NULL,
  `palavras_id1` INT NOT NULL,
  PRIMARY KEY (`palavras_id`, `palavras_id1`),
  INDEX `fk_palavras_has_palavras_palavras2_idx` (`palavras_id1` ASC),
  INDEX `fk_palavras_has_palavras_palavras1_idx` (`palavras_id` ASC),
  CONSTRAINT `fk_palavras_has_palavras_palavras1`
    FOREIGN KEY (`palavras_id`)
    REFERENCES `mydb`.`palavras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_palavras_has_palavras_palavras2`
    FOREIGN KEY (`palavras_id1`)
    REFERENCES `mydb`.`palavras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dicionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dicionario` (
  `id_dicionario` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `autor` VARCHAR(45) NULL,
  `editora` VARCHAR(45) NULL,
  PRIMARY KEY (`id_dicionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pertence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pertence` (
  `table1_id_dicionario` INT NOT NULL,
  `palavras_id` INT NOT NULL,
  PRIMARY KEY (`table1_id_dicionario`, `palavras_id`),
  INDEX `fk_table1_has_palavras_palavras1_idx` (`palavras_id` ASC),
  INDEX `fk_table1_has_palavras_table11_idx` (`table1_id_dicionario` ASC),
  CONSTRAINT `fk_table1_has_palavras_table11`
    FOREIGN KEY (`table1_id_dicionario`)
    REFERENCES `mydb`.`dicionario` (`id_dicionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_has_palavras_palavras1`
    FOREIGN KEY (`palavras_id`)
    REFERENCES `mydb`.`palavras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
