-- MySQL Script generated by MySQL Workbench
-- Mon Oct 23 19:06:12 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dicionario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dicionario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dicionario` DEFAULT CHARACTER SET utf8 ;
USE `dicionario` ;

-- -----------------------------------------------------
-- Table `dicionario`.`palavras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dicionario`.`palavras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `palavra` VARCHAR(45) NULL,
  `pronuncia` VARCHAR(45) NULL,
  `origem` VARCHAR(45) NULL,
  `significado` VARCHAR(120) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dicionario`.`sinonimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dicionario`.`sinonimo` (
  `palavras_id` INT NOT NULL,
  `palavras_id1` INT NOT NULL,
  PRIMARY KEY (`palavras_id`, `palavras_id1`),
  INDEX `fk_palavras_has_palavras_palavras1_idx` (`palavras_id1` ASC),
  INDEX `fk_palavras_has_palavras_palavras_idx` (`palavras_id` ASC),
  CONSTRAINT `fk_palavras_has_palavras_palavras`
    FOREIGN KEY (`palavras_id`)
    REFERENCES `dicionario`.`palavras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_palavras_has_palavras_palavras1`
    FOREIGN KEY (`palavras_id1`)
    REFERENCES `dicionario`.`palavras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dicionario`.`dicionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dicionario`.`dicionario` (
  `id_dicionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `autor` VARCHAR(45) NULL,
  `editora` VARCHAR(45) NULL,
  PRIMARY KEY (`id_dicionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dicionario`.`pertence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dicionario`.`pertence` (
  `table1_id_dicionario` INT NOT NULL,
  `palavras_id` INT NOT NULL,
  PRIMARY KEY (`table1_id_dicionario`, `palavras_id`),
  INDEX `fk_dicionario_has_palavras_palavras1_idx` (`palavras_id` ASC),
  INDEX `fk_dicionario_has_palavras_dicionario1_idx` (`table1_id_dicionario` ASC),
  CONSTRAINT `fk_dicionario_has_palavras_dicionario1`
    FOREIGN KEY (`table1_id_dicionario`)
    REFERENCES `dicionario`.`dicionario` (`id_dicionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dicionario_has_palavras_palavras1`
    FOREIGN KEY (`palavras_id`)
    REFERENCES `dicionario`.`palavras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
